# Generated by Django 5.0.1 on 2025-10-24 02:17

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='강의 제목')),
                ('description', models.TextField(verbose_name='강의 설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=courses.models.course_thumbnail_path, verbose_name='썸네일')),
                ('is_published', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('lectures_count', models.PositiveIntegerField(default=0, verbose_name='레슨 수')),
                ('total_duration', models.PositiveIntegerField(default=0, verbose_name='총 재생시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='강사')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의 목록',
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instructor', '-created_at'], name='courses_instruc_ec1f8d_idx'), models.Index(fields=['is_published', '-created_at'], name='courses_is_publ_454583_idx')],
            },
        ),
    ]
