# Generated by Django 5.0.1 on 2025-10-24 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='레슨 제목')),
                ('content_type', models.CharField(choices=[('text', '텍스트'), ('video', '비디오 업로드'), ('link', '외부 링크'), ('file', '첨부파일')], max_length=10, verbose_name='콘텐츠 타입')),
                ('content_text', models.TextField(blank=True, verbose_name='텍스트 내용')),
                ('video_url', models.URLField(blank=True, verbose_name='외부 비디오 URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='재생시간(초)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.course', verbose_name='강의')),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='media_files.mediafile', verbose_name='미디어 파일')),
            ],
            options={
                'verbose_name': '레슨',
                'verbose_name_plural': '레슨 목록',
                'db_table': 'lectures',
                'ordering': ['course', 'order'],
                'indexes': [models.Index(fields=['course', 'order'], name='lectures_course__3d4344_idx')],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
