# Generated by Django 5.0.1 on 2025-10-24 02:17

import django.db.models.deletion
import media_files.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=media_files.models.media_file_path, validators=[media_files.models.validate_file_size, media_files.models.validate_file_extension], verbose_name='파일')),
                ('file_type', models.CharField(choices=[('video', '비디오'), ('document', '문서'), ('image', '이미지')], max_length=10, verbose_name='파일 타입')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 타입')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '미디어 파일',
                'verbose_name_plural': '미디어 파일 목록',
                'db_table': 'media_files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_by', '-uploaded_at'], name='media_files_uploade_b38433_idx'), models.Index(fields=['file_type'], name='media_files_file_ty_6d2622_idx')],
            },
        ),
    ]
